//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Queue.Models.IRepository.IFLH
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ct_Eventos
    {
        public int Int_IdEvento { get; set; }
        public string Txt_Evento { get; set; }
        public string Txt_EventoCode { get; set; }
    }
}
