//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Queue.Models.IRepository.IFLH
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_EventosInvitado
    {
        public int Int_IdRegistro { get; set; }
        public Nullable<int> Int_IdInvitado { get; set; }
        public Nullable<bool> Bol_Evento1 { get; set; }
        public Nullable<bool> Bol_Evento2 { get; set; }
        public Nullable<bool> Bol_Evento3 { get; set; }
        public Nullable<System.DateTime> Fec_Alta { get; set; }
        public Nullable<int> Bol_Validado { get; set; }
    }
}
