//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Queue.Models.IRepository.IFLH
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_RegistroInvitados
    {
        public int Int_IdRegistro { get; set; }
        public string Txt_Correo { get; set; }
        public string Txt_Nombre { get; set; }
        public string Txt_Contraseña { get; set; }
        public Nullable<decimal> Num_Telefono { get; set; }
        public Nullable<System.DateTime> Fec_Alta { get; set; }
        public string Txt_Token { get; set; }
        public string Txt_QR { get; set; }
        public Nullable<int> Int_Status { get; set; }
    }
}
